foreground            #ffdad4
background            #200e0c
selection_foreground  #680100
selection_background  #ffb4a8
url_color             #a5c8ff
cursor                #ffb4a8
cursor_text_color     #680100

color0   #200e0c
color1   #ffb4ab
color2   #ffb4a8
color3   #a5c8ff
color4   #ffb4a8
color5   #a5c8ff
color6   #2f92fb
color7   #ffdad4

color8   #b08781
color9   #ffb4ab
color10  #ffb4a8
color11  #a5c8ff
color12  #ffb4a8
color13  #a5c8ff
color14  #2f92fb
color15  #ffdad4

tab_bar_background              #200e0c
tab_bar_margin_color            #200e0c
active_tab_foreground           #680100
active_tab_background           #ffb4a8
inactive_tab_foreground         #e9bcb5
inactive_tab_background         #200e0c
